/**
 * Emit `ALTER TABLE … ADD COLUMN IF NOT EXISTS …` for every column in the
 * Drizzle schema.
 *
 * ## Why this is needed
 *
 * `scripts/catch-up-schema.sql` is built from the migrations, and every table
 * in it is created with `CREATE TABLE IF NOT EXISTS`. That heals a *missing
 * table* but does nothing for a table that exists with **missing columns** —
 * `IF NOT EXISTS` sees the table, skips, and leaves the drift in place.
 *
 * That is exactly the shape of the sign-in outage: `users` existed, and one
 * column (`onboarding_completed_at`) did not. The two explicit `ADD COLUMN`s in
 * migration 0021 happened to cover that one. Nothing covered the general case,
 * so a database missing `users.coins` — or any of a dozen others the app
 * selects — would still fail after running the catch-up script, with an error
 * that looks identical.
 *
 * This generator closes that: one idempotent `ADD COLUMN IF NOT EXISTS` per
 * column, for every table.
 *
 * ## The NOT NULL rule
 *
 * A `NOT NULL` column with no default cannot be added to a table that already
 * has rows — Postgres has nothing to put in it. Those are emitted **nullable**,
 * with a comment, rather than as a statement that would abort the script. That
 * is the safe direction: a nullable column the app expects to be non-null is a
 * data problem to fix deliberately; a failed migration is an outage.
 *
 *     npx tsx scripts/generate-column-heal.ts
 */
import { getTableColumns, is } from 'drizzle-orm';
import { PgTable } from 'drizzle-orm/pg-core';
import * as schema from '../src/db/schema';

interface Emitted {
  sql: string;
  /** Set when the column had to be relaxed to nullable to stay safe. */
  relaxed?: string;
}

/**
 * `defaultNow()` and `defaultRandom()` arrive as a drizzle `SQL` object whose
 * only chunk is the raw expression. Rendering those matters: without it
 * `created_at` and every `id` would be emitted NULLABLE (no literal default to
 * satisfy NOT NULL), which is both noisier and weaker than it needs to be.
 */
function sqlExpression(value: object): string | null {
  const chunks = (value as { queryChunks?: Array<{ value?: unknown }> }).queryChunks;
  if (!Array.isArray(chunks) || chunks.length !== 1) return null;
  const raw = chunks[0]?.value;
  const text = Array.isArray(raw) ? raw.join('') : typeof raw === 'string' ? raw : null;
  if (!text) return null;
  // Only allow the handful this schema actually uses. Anything else is left to
  // the migrations rather than reconstructed from an internal representation.
  return /^(now\(\)|gen_random_uuid\(\)|now\(\) \+ interval '[^']+')$/.test(text.trim())
    ? text.trim()
    : null;
}

function defaultLiteral(column: { default: unknown }): string | null {
  const value = column.default;
  if (value === undefined) return null;
  if (value === null) return 'NULL';
  if (typeof value === 'string') return `'${value.replace(/'/g, "''")}'`;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (typeof value === 'object') {
    const expr = sqlExpression(value);
    if (expr) return expr;
    return `'${JSON.stringify(value)}'`;
  }
  return null;
}

function emitTable(tableName: string, table: PgTable): Emitted[] {
  const out: Emitted[] = [];
  for (const column of Object.values(getTableColumns(table))) {
    const type = column.getSQLType();
    const literal = defaultLiteral(column as never);

    let clause = `ALTER TABLE "${tableName}" ADD COLUMN IF NOT EXISTS "${column.name}" ${type}`;
    if (literal !== null) clause += ` DEFAULT ${literal}`;

    // NOT NULL is only safe when there is something to backfill with.
    if (column.notNull && literal !== null) {
      clause += ' NOT NULL';
      out.push({ sql: `${clause};` });
    } else if (column.notNull) {
      out.push({
        sql: `${clause};`,
        relaxed: `${tableName}.${column.name}`,
      });
    } else {
      out.push({ sql: `${clause};` });
    }
  }
  return out;
}

function main(): void {
  const lines: string[] = [];
  const relaxed: string[] = [];

  lines.push('-- ' + '='.repeat(74));
  lines.push('-- column-heal — generated by scripts/generate-column-heal.ts, do not hand-edit');
  lines.push('--');
  lines.push('-- One idempotent ADD COLUMN per column in the Drizzle schema. The migrations');
  lines.push('-- above create tables with CREATE TABLE IF NOT EXISTS, which heals a missing');
  lines.push('-- TABLE but silently skips a table that exists with missing COLUMNS — the exact');
  lines.push('-- shape of the sign-in outage (`users` existed; `onboarding_completed_at` did');
  lines.push('-- not). This pass closes that gap for every table, not just the two columns');
  lines.push('-- migration 0021 happened to name.');
  lines.push('-- ' + '='.repeat(74));
  lines.push('');

  const names = Object.keys(schema).sort();
  for (const name of names) {
    const value = (schema as Record<string, unknown>)[name];
    if (!is(value as never, PgTable as never)) continue;
    const table = value as PgTable;
    const tableName = (table as unknown as { [k: symbol]: string })[
      Symbol.for('drizzle:Name') as unknown as symbol
    ];
    if (!tableName) continue;

    const emitted = emitTable(tableName, table);
    lines.push(`-- ${tableName}`);
    for (const e of emitted) {
      lines.push(e.sql);
      if (e.relaxed) relaxed.push(e.relaxed);
    }
    lines.push('');
  }

  if (relaxed.length > 0) {
    lines.push('-- ' + '-'.repeat(74));
    lines.push('-- Emitted NULLABLE despite being NOT NULL in the schema, because they have no');
    lines.push('-- default and Postgres cannot add a NOT NULL column to a table with rows:');
    for (const r of relaxed) lines.push(`--   ${r}`);
    lines.push('-- If any of these is genuinely missing in your database, backfill it and add');
    lines.push('-- the constraint deliberately. A failed migration is worse than a nullable');
    lines.push('-- column, which is why the script does not attempt it.');
    lines.push('-- ' + '-'.repeat(74));
    lines.push('');
  }

  process.stdout.write(lines.join('\n'));
}

main();
